const NS_DATA_SERVICES='servicesSystem';
const SET_LOADING_STEP = `${NS_DATA_SERVICES}/setGlobalLoading`;
const GET_ALL_SERVICES = `${NS_DATA_SERVICES}/getAllService`;
const SAVE_ALL_SERVICES = `${NS_DATA_SERVICES}/saveAllService`;

const CREATE_SERVICE_REQUEST = `${NS_DATA_SERVICES}/createServiceRequest`;
const CREATE_SERVICE_SUCCESS = `${NS_DATA_SERVICES}/createServiceSuccess`;

const DELETE_SUCCESS = `${NS_DATA_SERVICES}/DELETE_SUCCESS`;
const UPDATE_SUCCESS =`${NS_DATA_SERVICES}/UPDATE_SUCCESS`;
export {
    SET_LOADING_STEP,
    GET_ALL_SERVICES,
    SAVE_ALL_SERVICES,
    CREATE_SERVICE_REQUEST,
    CREATE_SERVICE_SUCCESS,
    DELETE_SUCCESS,
    UPDATE_SUCCESS
}